### ISSUE TITLE
In-game Mouse Capture sometimes gets the game stuck in pause mode

### ISSUE THREAD

**Issue by olofson** [olofson/kobodeluxe#1]
The "In-game Mouse Capture" (mousecapture) has been reported to cause the game to get stuck in a paused state, which there seems to be no way out of. Disabling mousecapture avoids that issue.

I've failed to reproduce this issue - until just now, building and running the game under WSL with Ubuntu 18.04 LTS on Windows10, against Xming. Hopefully, it's the same issue, and I can look into why it happens.

**Comment by olofson** [comment]
This is most likely Debian bug #909244, for which there is a patch. (I'm reviewing those for the "revived" Kobo Deluxe repo I just added here.)

**Comment by darshan-** [comment]
I just ran into this on Arch Linux, using Arch's community/kobodeluxe 0.5.1-8 package.  I can't tell from a brief look at things if  a358972 is included in that build or not.  I was grateful for this bug report, because turning off "In-game Mouse Capture" allowed me to play, and I was about to give up in frustration after trying literally every key on my keyboard and then Googling for a few minutes.  Figured it was worth mentioning.  Thanks for maintaining this classic gem!

**Comment by olofson** [comment]
Thank you! If you're seeing the issue, the fix is most likely not applied. It appears that only some distros include it, most likely because the issue only seems to trigger under certain conditions. (I never saw it myself back when I was working more actively on the game, and wasn't even aware of it until much later.)

Either way, the fix is now "official" (along with the move to SDL2 and various other stuff) - but I need to get to the point of making an actual release as well, so distros can start picking it up. :-)
